### ISSUE TITLE
Save the ExperimentalEmulator error

### ISSUE THREAD

**Issue by AFilipaAlmeida** [sustainable-processes/summit#104]
* Operating System: Windows 10 
* Python version: Python 3.7.10 through anaconda
* summit version used: current summit version

**Description**

I want to use summit for my data.  My intention is to compare the results obtained by summit with the model developed by me.
I would appreciate some help with the creation a new benchmark with my dataset. 

I followed all the steps in the tutorial:
1)Create the domain: I introduced all continuosvariable and defined the range of values in bounds;
2) Load Data: I imported the data in CSV format, added the row below column name with the word DATA;
3) Train the Emulator: I defined the dataset, domain and name for the model in ExperimentalEmulator; 

ds = DataSet.read_csv('C:\\Users\\afalmeida\\PycharmProjects\\Summit\\dataset.csv')
emul = ExperimentalEmulator(model_name='molecule', domain=domain, dataset=ds)
emul.train(shuffle=True, max_epochs=1000, cv_fold=5)

4)Evaluate Emulator: I did a parity plot;
5) Saving and Loading Emulators: I applied the code to save files however I obtained an error.

![image](https://user-images.githubusercontent.com/74240882/112137812-a43b4580-8bc8-11eb-9d1e-7c6410070ff4.png)

How I can resolve this error?

**Comment by marcosfelt** [comment]
Try installing this version `pip install summit==0.8.0rc1`

**Comment by AFilipaAlmeida** [comment]
It works!! Summit==0.8.0rc1 resolves this issue
Thank  you very much!!!
