### ISSUE TITLE
Random forest or decision tree as regressor in ExperimentalEmulator

### ISSUE THREAD

**Issue by AFilipaAlmeida** [sustainable-processes/summit#131]
* Operating System: Windows 10
* Python version: Python 3.7.10 through anaconda
* summit version used: 0.8.0rc1

### Description
Test others regressor such as Random Forest or Decision Trees in ExperimentalEmulator

### What I Did
 I trying to create a new benchmark. 
Firstly, I created a domain but when, I tried to train/ test my benchmark the value of r2  score was not good. 
![image](https://user-images.githubusercontent.com/74240882/116405923-1803ea00-a828-11eb-8913-4afc3b048630.png)

By default, the regressor used is ANNregressor but I have a small dataset, it will possible to change this regressor to a random forest or decision tree to improve the value of r2  score?

**Comment by marcosfelt** [comment]
You might try using the cross-validation feature to change the number of hidden units in the neural network.
   ``` python
    from summit import *
    # Test grid search cross validation and training
    model_name = f"reizman_suzuki_case_1"
    domain = ReizmanSuzukiEmulator.setup_domain()
    ds = DataSet.read_csv(DATA_PATH / f"{model_name}.csv")
    exp = ExperimentalEmulator(model_name, domain, dataset=ds, regressor=ANNRegressor)
    params = {
        "regressor__net__module__hidden_units":  [10, 100, 500]
    }
    exp.train(cv_folds=5, random_state=100, search_params=params, verbose=0)
   ```
It's not possible to use other regressors from scikit-learn currently, but I would be happy to accept a PR enabling this functionality. You basically need to make a conditional that the NeuralNetRegressor is only created when a torch.nn.Module class is passed. See [here](https://github.com/sustainable-processes/summit/blob/1c373a7e8a0e9c4f4a8da23074e423af3d15cf59/summit/benchmarks/experimental_emulator.py#L361). Also, there would need to be some updates to the emulator saving and loading code.
