### ISSUE TITLE
TSEMO error

### ISSUE THREAD

**Issue by AFilipaAlmeida** [sustainable-processes/summit#147]
* Operating System: Windows 10
* Python version: Python 3.7.10 through anaconda
* summit version used: 0.8.0rc1

### Description

I'm trying to optimize a chemical rection with 8 inputs and 9 objectives through the TSEMO strategy. However when I use the runner to run closed loop optimisation obtained an error.

![image](https://user-images.githubusercontent.com/74240882/122101559-5a9b7900-ce0c-11eb-8dd4-a0da40dae660.png)

or when I applied the transform the issue I got was
![image](https://user-images.githubusercontent.com/74240882/122102020-e1505600-ce0c-11eb-987b-fc0e89999852.png)

Do you know how i can solve this issue? Thank you very much

**Comment by marcosfelt** [comment]
As a quick check, can you try generating 7,8 and 9 points using LHS, running them and then passing those to TSEMO? I am wondering if this has to do with the hypervolume calculation requiring a certain number of initial points, but I'm not sure.

```python
from summit import *

n_points = 9  # change this to 7, 8 or 9
lhs = LHS(emul.domain)
conditions = lhs.suggest_experiments(n_points)
results = emul.run_experiments(conditions)

tsemo = TSEMO(emul.domain)
tsemo.suggest_experiments(conditions, prev_res=results)
```

**Comment by AFilipaAlmeida** [comment]
New issues:
with n_point=7 
![image](https://user-images.githubusercontent.com/74240882/122472349-63c94900-cfb8-11eb-987c-fbdc9d6f9847.png)

with n_point=8 or 9 (the result was the same)
![image](https://user-images.githubusercontent.com/74240882/122471985-e1d92000-cfb7-11eb-9415-0c6fb5e0ebc6.png)

**Comment by marcosfelt** [comment]
Sorry about that, I wrote the code incorrectly

``` python
from summit import *

n_points = 9  # change this to 7, 8 or 9
lhs = LHS(emul.domain)
conditions = lhs.suggest_experiments(n_points)
results = emul.run_experiments(conditions)

tsemo = TSEMO(emul.domain)
tsemo.suggest_experiments(1, prev_res=results)
```
