### ISSUE TITLE
Expanding documentation

### ISSUE THREAD

**Issue by dswigh** [sustainable-processes/summit#154]
* Operating System: MacOS
* Python version: 3.9.5
* summit version used: 0.8.3

### Description

Reading documentation, specifically the tutorials and description of the Runner
https://gosummit.readthedocs.io/en/latest/runner.html

There were three things I couldn't find:
- How to access the results of the runner (ie needing to look up r.experiment.data where r is the Runner object)
- Code for generating figures like the one in neurips_paper_results.ipynb showing how the yield changes as more points are queried using different strategies. Right now there's only sample code for generating parity plots, which isn't useful for single objective optimisation.
- How to check current summit version ('summit --version' doesn't seem to work). I found the current version by attempting to reinstall it with pip install summit.

Thanks,
Daniel

**Comment by marcosfelt** [comment]
Would love to do this, but closing for now.
