### ISSUE TITLE
Numpy issue in strategies

### ISSUE THREAD

**Issue by njoseGIT** [sustainable-processes/summit#172]
* Operating System: Windows 10 Home Version 21H2 Build 19044.1645
* Python version: 3.10
* summit version used: 0.8.4
* Using pycharm

### Description

Was testing out the strategies module and ran into issues with numpy

### What I Did
scratch.py

from summit import *
import numpy as np

domain = Domain()

domain += ContinuousVariable(name="x_0",
                            description="reaction temperature in celsius",
                            bounds=[50, 100])

domain += ContinuousVariable(name="x_1",
                             description="flow of reactant a in mL/min",
                             bounds=[0.1, 0.5])

domain += ContinuousVariable(name="y_0",
                             description="yield",
                             bounds=[0.1, 0.5],
                             is_objective=True,
                             maximize=True)

domain += ContinuousVariable(name="y_1",
                             description="cost",
                             bounds=[0.1, 0.5],
                             is_objective=True,
                             maximize=True)

strategy = LHS(domain, random_state=np.random.RandomState(3))

results = strategy.suggest_experiments(5)

strategy_lhs = LHS(domain, random_state=np.random.RandomState(3))
results = strategy.suggest_experiments(5)
print(results)

strategy_tsemo = TSEMO(domain)
experiments = strategy_tsemo.suggest_experiments(5)
print(experiments)

Error message:

"C:\Users\njose\Dropbox (Cambridge CARES)\Python\idmt_codeshare\pyflab_CURRENT\venv\Scripts\python.exe" "C:/Users/njose/Dropbox (Cambridge CARES)/Python/idmt_codeshare/pyflab_CURRENT/scratch.py"
C:\Users\njose\Dropbox (Cambridge CARES)\Python\idmt_codeshare\pyflab_CURRENT\venv\lib\site-packages\torch\_masked\__init__.py:223: UserWarning: Failed to initialize NumPy: module compiled against API version 0xf but this version of numpy is 0xe (Triggered internally at  ..\torch\csrc\utils\tensor_numpy.cpp:68.)
  example_input = torch.tensor([[-3, -2, -1], [0, 1, 2]])
Traceback (most recent call last):
  File "C:\Users\njose\Dropbox (Cambridge CARES)\Python\idmt_codeshare\pyflab_CURRENT\scratch.py", line 25, in <module>
    strategy = LHS(domain, random_state=np.random.RandomState(3))
NameError: name 'np' is not defined

Process finished with exit code 1

**Comment by marcosfelt** [comment]
Hi Nick! I think I just need to push an new version from master. I will do that this morning!

**Comment by njoseGIT** [comment]
Hi Kobi,
I see! Thanks for the quick help!
Regards,
Nick

**Comment by marcosfelt** [comment]
Closing in favor of #162
