### ISSUE TITLE
Inconsisteny between tutorial and application in calling a benchmark

### ISSUE THREAD

**Issue by KevinBallu** [sustainable-processes/summit#181]
* Python version: 3.7 (I think)
* summit version used: last one (imported through collab)

### Description
When trying to assign an homemade trained benchmark to a variable: exp = emul() I get the following error:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)

[<ipython-input-20-cefc6926563c>](https://localhost:8080/#) in <module>()
----> 1 exp = emul()
      2 
      3 # Instantiate random sampling strategy
      4 strategy = Random(exp.domain)
      5 

TypeError: 'ExperimentalEmulator' object is not callable
---------------------------------------------------------------------------

The instruction works well when using a benchmark that is included in the software.
The instruction (seems to) work well when assigning by using: exp = emul

### What I Did

```bash
!pip install summit
from summit.benchmarks import ExperimentalEmulator
from summit.domain import *
from summit.utils.dataset import DataSet
import pkg_resources
import pathlib

%load_ext autoreload
%autoreload 2

domain = Domain()

# Decision variables and Objectives appended to domain

ds = DataSet.read_csv("my_data.csv")
emul = ExperimentalEmulator(model_name='my_model', domain=domain, dataset=ds)
emul.train(max_epochs=1000, cv_fold=2, test_size=0.2, verbose=0)
exp = emul()
```

**Comment by marcosfelt** [comment]
Hi Kevin!

You'll want to do something like this:
```python

!pip install summit
from summit.benchmarks import ExperimentalEmulator
from summit.domain import *
from summit.utils.dataset import DataSet
import pkg_resources
import pathlib

%load_ext autoreload
%autoreload 2

domain = Domain()

# Decision variables and Objectives appended to domain

ds = DataSet.read_csv("my_data.csv")
emul = ExperimentalEmulator(model_name='my_model', domain=domain, dataset=ds)
emul.train(max_epochs=1000, cv_fold=2, test_size=0.2, verbose=0)
exp = emul.run_experiments(conditions)

```

Where `conditions` is a DataSet with your experimental conditions.

See here for an example: https://gosummit.readthedocs.io/en/latest/experiments_benchmarks/implemented_benchmarks.html#cross-coupling-emulator-benchmarks

Hope that helps!
