### ISSUE TITLE
Bugs in SnAr benchmark function?

### ISSUE THREAD

**Issue by Yujikaiya** [sustainable-processes/summit#185]
I'm not so sure but, If my understanding is correct, the code below
` r[3] = k_a * C[0] * C[1] - k_d * C[1] * C[3]`
should be
` r[3] = k_b * C[0] * C[1] - k_d * C[1] * C[3]`

It would be appreciated if you check this when you have time.

**Comment by marcosfelt** [comment]
Hi Yuji! I think you might be right about this. Let me check tomorrow. Thanks for bringing it up!
