### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by TedOiler** [sustainable-processes/summit#190]
* Operating System: MacOS Monterey 12.4
* Python version: 3.9.7
* summit version used: 0.8.5

### Description

I get an error when importing summit. Installing worked fine, but when I import it I get an sklearn error.

### What I Did

```python
import summit
```

### Error 
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/var/folders/bb/tzggm8cx2f5fyxfhdmmhn7j40000gn/T/ipykernel_3477/2754492982.py in <module>
----> 1 from summit.benchmarks import SnarBenchmark
      2 from summit.strategies import NelderMead, MultitoSingleObjective
      3 from summit.run import Runner
      4 from matplotlib import pyplot as plt

~/opt/anaconda3/lib/python3.9/site-packages/summit/__init__.py in <module>
     17 from summit.domain import *
     18 from summit.experiment import *
---> 19 from summit.run import *
     20 from summit.strategies import *
     21 from summit.benchmarks import *

~/opt/anaconda3/lib/python3.9/site-packages/summit/run.py in <module>
      1 from summit.strategies import Strategy, strategy_from_dict
      2 from summit.experiment import Experiment
----> 3 from summit.benchmarks import *
      4 from summit.utils.multiobjective import pareto_efficient, hypervolume
      5 from summit import get_summit_config_path

~/opt/anaconda3/lib/python3.9/site-packages/summit/benchmarks/__init__.py in <module>
      1 from .snar import SnarBenchmark
      2 from .test_functions import Himmelblau, Hartmann3D, ThreeHumpCamel, DTLZ2, VLMOP2
----> 3 from .experimental_emulator import *
      4 from .MIT import *

~/opt/anaconda3/lib/python3.9/site-packages/summit/benchmarks/experimental_emulator.py in <module>
     19     ParameterGrid,
     20 )
---> 21 from sklearn.model_selection._search import BaseSearchCV, _check_param_grid
     22 from sklearn.base import (
     23     BaseEstimator,

ImportError: cannot import name '_check_param_grid' from 'sklearn.model_selection._search' (/Users/thodorisladas/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_search.py)

**Comment by marcosfelt** [comment]
Hey Ted! Thanks for raising this issue. I have fix commuted and will push a new version tomorrow.

**Comment by marcosfelt** [comment]
The new version on pypi (0.8.6) should fix! So do:
```
pip install -U summit
```
