### ISSUE TITLE
Non-existing module entmoot.optimizer

### ISSUE THREAD

**Issue by ilario** [sustainable-processes/summit#212]
Summit 0.8.7

Testing ENTMOOT I observed this error:
```
ModuleNotFoundError: No module named 'entmoot'
```
caused by this line:

https://github.com/sustainable-processes/summit/blob/249751d57c3603fda99437b35656a1d78e2f0371/summit/strategies/entmoot.py#L253

**Comment by marcosfelt** [comment]
It's here: https://gosummit.readthedocs.io/en/latest/installation.html#installation

**Comment by ilario** [comment]
Oh! I missed that! Thanks!!
