### ISSUE TITLE
Difficulties with installation

### ISSUE THREAD

**Issue by sqbl** [sustainable-processes/summit#71]
* Operating System: Windows10
* Python version: 3.7.9 (from anaconda)
* summit version used: 0.6.0

### Description

Trying to install summit in a fresh anaconda env failed. Specifically, gryffin is coursing issues due to a "/" in it's "setup.py". Furthermore, gryffin has quiet many failing dependencies that will need to be installed "manually" by the user (e.g. the entire C++ environment, and specific version numbers of torch) 

### What I Did

Initially, I tried "pip install summit", which would fail due to the "/" in setup.py. I manually cloned gryffin, changed the "/" and tried to install it again. After resolving numerous errors related to my lack of a C++ environment and a specific download of torch (pip install -f https://download.pytorch.org/whl/torch_stable.html torch===1.4.0) (which was not doable by pip), I succeeded. With the gryffin dependency done, I tried to "pip install summit" again, but found that my local workaround had led to the installed version of gryffin being: "0+untagged.10.g4ff6cda.dirty". So now pip tries to download it again to install a version between 0.1.1 and 0.2.0.

I believe that a change in the setup.py of gryffin and a better description of the dependencies of summit could help other potential new users. (I'm writing this error report here, in the believe that the maintainer of summit can reach out to the maintainers of gryffin as was done in aspuru-guzik-group/gryffin#3. I will also report the behaviour in gryffin repo.

```bash
pip install summit

>Collecting gryffin<0.2.0,>=0.1.1
  Using cached gryffin-0.1.1.tar.gz (586 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\sqbl\AppData\Local\Continuum\anaconda3\envs\Summit\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\sqbl\\AppData\\Local\\Temp\\pip-install-y968kzpr\\gryffin\\setup.py'"'"'; __file__='"'"'C:\\Users\\sqbl\\AppData\\Local\\Temp\\pip-install-y968kzpr\\gryffin\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\sqbl\AppData\Local\Temp\pip-pip-egg-info-pljb5vv1'
         cwd: C:\Users\sqbl\AppData\Local\Temp\pip-install-y968kzpr\gryffin\
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\sqbl\AppData\Local\Temp\pip-install-y968kzpr\gryffin\setup.py", line 50, in <module>
        packages=find_packages('./src/'),
      File "C:\Users\sqbl\AppData\Roaming\Python\Python37\site-packages\setuptools\__init__.py", line 71, in find
        convert_path(where),
      File "C:\Users\sqbl\AppData\Local\Continuum\anaconda3\envs\Summit\lib\distutils\util.py", line 112, in convert_path
        raise ValueError("path '%s' cannot end with '/'" % pathname)
    ValueError: path './src/' cannot end with '/'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by marcosfelt** [comment]
Thanks for this issue. I'm aware of this issue and will correct the problem with gryffin too. I actually am the one who put gryffin on pypi, so I can make the adjustment.

I created a branch without gryffin if you want a stopgap to use immediately:
```
pip install git+https://github.com/sustainable-processes/summit.git@stopgap#egg=summit
```

**Comment by marcosfelt** [comment]
The most recent version of summit (0.8.0rc0) should resolve this issue. Feel free to re-open if necessary.
